title: Bob Sherin # your name (or website title) here
logo: "/images/drones_thumbpic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  University of Maryland Baltimore County
  <br>
  <i>Bachelor of Science, Information Systems, May 2020</i>
  <br><br>
  The Community College of Baltimore County
  <br>
  <i>Certificate, Advanced Geospatial Applications, May 2020</i>
  <br>
  <i>Associate of Science, Computer Science, Cum Laude, May 2018</i>
  <br>
  <i>Certificate, Computer Programming, May 2017</i>
  <br><br>
  <a href="https://www.geosherin.com/mexico/">geoSherin.com/Mexico</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/bobsherin/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
